
/**
 * ActionEntityDetailsGeneralTab.java
 *
 * Generated by actions.xsl and xalan
 *
 * DO NOT MODIFY BY HAND!!!
 *
 * This code is licensed under a Creative Commons License: http://creativecommons.org/licenses/by-sa/1.0/
 *
 *
 */
package com.braithwaite-lee.action.Entitydetails;

import com.braithwaite-lee.form.TabViewDispatchElectionForm;
import com.braithwaite-lee.form.EntityGeneralForm;
import com.braithwaite-lee.action.common.ButtonLookupDispatchAction;
import com.braithwaite-lee.control.ActionMapping;
import com.braithwaite-lee.delegate.EntityDelegate;
import org.apache.struts.action.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import junit.framework.Assert;

public final class ActionEntityDetailsGeneralTab
extends ButtonLookupDispatchAction
{
                  
public ActionForward loadPage(
        final ActionMapping mapping,
        final ActionForm requestForm,
        final HttpServletRequest request,
        final HttpServletResponse response
        )
throws Exception
{
    ActionErrors errors = new ActionErrors();
    ActionForward actionForward = mapping.findForward("EntityDetailsGeneral");



        EntityGeneralForm resultsForm = EntityDelegate.Instance().handleActionEntityDetailsGeneralTab (
                        (TabViewDispatchElectionForm) requestForm,
                        request
                );
                
        ActionMapping myMapping = (ActionMapping) mapping;

        setResultsForm(mapping, request, "EntityGeneralForm", resultsForm);


    return actionForward;

}

}